version: '3'
services:
  front-builder:
    container_name: front-builder
    image: front-builder
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - ~/html:/var/www/html:rw
