version: '3'
volumes:
  front:
services:
  web:
    container_name: web
    image: web
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - front:/var/www/html
  server:
    container_name: server
    image: nginx:1.23-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - front:/var/www/html:ro
      - ./nginx:/etc/nginx/conf.d/:ro