version: '3'
services:
  web-builder:
    container_name: web-builder
    image: web-builder
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - /home/ubuntu/web-build:/var/www/html:rw
