on:
  push:
    branches:
      - main

name: Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          sudo rm -rf ~/html/*
          docker compose up -d
      
      - name: Clean-up
        run: docker system prune -f